### ISSUE TITLE
Provider engine panic on explore recursive edge with no parent

### ISSUE THREAD

**Issue by masih** [filecoin-project/index-provider#144]
```
2022-01-18T14:04:13.499+0200	INFO	provider/engine	engine/linksystem.go:45	Retrieved advertisement from datastore	{"cid": "baguqeeqqj2huagbnkzkxipqqi2j2vce7ya", "size": 958}
panic: Traversed Explore Recursive Edge Node With No Parent

goroutine 153112616 [running]:
github.com/ipld/go-ipld-prime/traversal/selector.ExploreRecursiveEdge.Decide(...)
	/root/code/pkg/mod/github.com/ipld/go-ipld-prime@v0.14.3/traversal/selector/exploreRecursiveEdge.go:31
github.com/ipld/go-ipld-prime/traversal/selector.ExploreRecursive.Decide(...)
	/root/code/pkg/mod/github.com/ipld/go-ipld-prime@v0.14.3/traversal/selector/exploreRecursive.go:165
github.com/ipld/go-ipld-prime/traversal.Progress.walkAdv(0xc038df92c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00cfc0310, ...)
	/root/code/pkg/mod/github.com/ipld/go-ipld-prime@v0.14.3/traversal/walk.go:159 +0x83
github.com/ipld/go-ipld-prime/traversal.Progress.WalkAdv(0xc038df92c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00cfc0310, ...)
	/root/code/pkg/mod/github.com/ipld/go-ipld-prime@v0.14.3/traversal/walk.go:147 +0xd9
github.com/ipfs/go-graphsync/ipldutil.(*traverser).start.func1(0xc011069900)
	/root/code/pkg/mod/github.com/ipfs/go-graphsync@v0.11.5/ipldutil/traverser.go:230 +0x3d1
created by github.com/ipfs/go-graphsync/ipldutil.(*traverser).start
	/root/code/pkg/mod/github.com/ipfs/go-graphsync@v0.11.5/ipldutil/traverser.go:198 +0x55
```

**Comment by masih** [comment]
This is an issue in IPLD where a parsed selector can still cause a panic.[ graphsync does parse the selector ](https://github.com/ipfs/go-graphsync/blob/v0.11.5/ipldutil/traverser.go#L218) before traversal. Until it is guaranteed by IPLD that a parsed selector will not panic consider wrapping provider code with `recover` to catch any potential `panic`s.
